[package]
name = "talsynte"
version = "0.1.0"
authors = ["snarkusius <marcus@lengquist.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3"
